### ISSUE TITLE
Locked items: Some unreachable locations are added in the spoiler logs by mistake

### ISSUE THREAD

**Issue by sbzappa** [Moppu/SecretOfManaRandomizer#67]
SEED: 2C1741B78178BC9F
OPTIONS: mode=open opAllowLockedItems=yes opCharacters=find1L1 opChestFreq=high opComplexity=hard opEnemies=vanilla opFlammieDrumInLogic=yes opGoal=mtr opGoldDropMul=100 opLogic=restrictive opStartChar=sprite opStatusAilments=type version=1.43 opNumSeeds=7 opStartGold=300

When looking at the spoiler logs, the locations

```
16:24:22 - [spoiler] luna item 1 (spells) [Axe orb]
16:24:22 - [spoiler]   needs: 
16:24:22 - [spoiler]   shade spells
16:24:22 - [spoiler]   moon seed
16:24:22 - [spoiler] luna item 2 (seed) [nothing]
16:24:22 - [spoiler]   needs: 
16:24:22 - [spoiler]   shade spells
16:24:22 - [spoiler]   moon seed
```

are listed as non reachable, but both the shade spells and the moon seed are accessible in the game (and required).

**Comment by Cyb3RGER** [comment]
```
15:32:54 - [spoiler] lumina seed [axe]
15:32:54 - [spoiler]   needs: 
15:32:54 - [spoiler]   gold tower key
15:32:54 - [spoiler]   light seed
15:32:54 - [spoiler] shade palace chest [gold tower key]
15:32:54 - [spoiler]   needs: 
15:32:54 - [spoiler]   axe
15:32:54 - [spoiler] matango inn javelin orb chest [shade spells]
15:32:54 - [spoiler]   needs: 
15:32:54 - [spoiler]   axe
```
so this technically correct as gold tower key and axe are self locking and shade needs axe as per logic.
shade spells is also not required.

that being said the logic for matango inn is wrong tho, it should be axe or flammie drum but similar issues apply to many other locations like the 2nd half pure lands and mana fort which require sword instead of sword or axe afaict (unless I am missing something how locked by sword gets resolved).
